// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
//  import 'firebase_options.dart';
// /// // ...
//    await Firebase.initializeApp(
//    options: DefaultFirebaseOptions.currentPlatform,
//  );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO4JIRh5UkK44-Ye1j_7xUtzegI0iFgyw',
    appId: '1:421857665314:web:dadd9c12546d25de3b057b',
    messagingSenderId: '421857665314',
    projectId: 'vehicle-pooling-79f06',
    authDomain: 'vehicle-pooling-79f06.firebaseapp.com',
    storageBucket: 'vehicle-pooling-79f06.appspot.com',
    measurementId: 'G-S78PXYWRPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLIA5xbNMvcyoGCA6HI16zn2XdSMo0p8g',
    appId: '1:421857665314:android:032dede65f2421413b057b',
    messagingSenderId: '421857665314',
    projectId: 'vehicle-pooling-79f06',
    storageBucket: 'vehicle-pooling-79f06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCe__OdVEFsMh_FT1ZnmKLBN6VPHiDIj3c',
    appId: '1:421857665314:ios:cec5147f465bae723b057b',
    messagingSenderId: '421857665314',
    projectId: 'vehicle-pooling-79f06',
    storageBucket: 'vehicle-pooling-79f06.appspot.com',
    iosClientId: '421857665314-sf2l5kdv0j5a60739tbi832ics2lk9sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fairshare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCe__OdVEFsMh_FT1ZnmKLBN6VPHiDIj3c',
    appId: '1:421857665314:ios:cec5147f465bae723b057b',
    messagingSenderId: '421857665314',
    projectId: 'vehicle-pooling-79f06',
    storageBucket: 'vehicle-pooling-79f06.appspot.com',
    iosClientId: '421857665314-sf2l5kdv0j5a60739tbi832ics2lk9sn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fairshare',
  );
}

